# DistroShelf - distro implementation contracts
# Engines own transaction semantics and scheduling.
# Each distro owns acquisition, installation, artifact-export and functional tests.

function New-StageTest { param([string]$Name,[string]$Command,[int]$ExpectedExitCode=0,[string]$ExpectedOutput) [pscustomobject][ordered]@{Name=$Name;Command=$Command;ExpectedExitCode=$ExpectedExitCode;ExpectedOutput=$ExpectedOutput} }
function New-StageContract {
    param([string]$Id,[string[]]$Depends,[string]$PackageManager,[string[]]$TrackAcquire,[string[]]$TrackInstall,[object[]]$TrackTests,[string[]]$ProfileInstall,[object[]]$ProfileTests,[string]$ExportType,[string]$ExportValue,[string]$Kind='dependency',[string]$ParallelGroup)
    [pscustomobject][ordered]@{Id=$Id;Depends=@($Depends);Kind=$Kind;ParallelGroup=$ParallelGroup;PackageManager=$PackageManager;Track=[pscustomobject][ordered]@{Acquire=@($TrackAcquire);Install=@($TrackInstall);Tests=@($TrackTests);ExportType=$ExportType;ExportValue=$ExportValue};Profile=[pscustomobject][ordered]@{Install=@($ProfileInstall);Tests=@($ProfileTests)}}
}

function Get-DistroShelfAptStages {
    param([string]$Distro)
    $pod=@(New-StageTest 'podman-command' 'command -v podman';New-StageTest 'podman-version' 'podman --version';New-StageTest 'podman-info' 'podman info --format json')
    $db=@(New-StageTest 'distrobox-command' 'command -v distrobox';New-StageTest 'distrobox-version' 'distrobox --version')
    $fp=@(New-StageTest 'flatpak-command' 'command -v flatpak';New-StageTest 'flatpak-version' 'flatpak --version')
    return @(
        (New-StageContract 'rootfs' @() 'apt' @() @() @(New-StageTest 'os-release' 'test -s /etc/os-release') @() @() 'none' '' 'rootfs' 'bootstrap'),
        (New-StageContract 'podman' @('rootfs') 'apt' @('apt-get update','apt-get download podman') @('apt-get -y install podman') $pod @('apt-get -y install --no-download podman') $pod 'apt-cache' '' 'dependency' 'container-runtime'),
        (New-StageContract 'distrobox' @('rootfs','podman') 'apt' @('apt-get download distrobox') @('apt-get -y install distrobox') $db @('apt-get -y install --no-download distrobox') $db 'apt-cache' '' 'dependency' 'container-runtime'),
        (New-StageContract 'flatpak' @('rootfs') 'apt' @('apt-get download flatpak') @('apt-get -y install flatpak') $fp @('apt-get -y install --no-download flatpak') $fp 'apt-cache' '' 'dependency' 'desktop-runtime'),
        (New-StageContract 'flathub' @('rootfs','flatpak') 'apt' @('mkdir -p /tmp/ds-flathub; curl -fsSL https://dl.flathub.org/repo/flathub.flatpakrepo -o /tmp/ds-flathub/flathub.flatpakrepo') @('flatpak remote-add --if-not-exists flathub /tmp/ds-flathub/flathub.flatpakrepo') @(New-StageTest 'flathub-remote' 'flatpak remotes --columns=name | grep -Fx flathub') @() @(New-StageTest 'flathub-remote' 'flatpak remotes --columns=name | grep -Fx flathub') 'wsl-path' '/tmp/ds-flathub' 'dependency' 'desktop-runtime'),
        (New-StageContract 'distroshelf' @('rootfs','distrobox','flatpak','flathub') 'apt' @('flatpak install -y flathub com.ranfdev.DistroShelf') @() @(New-StageTest 'distroshelf-install' 'flatpak info com.ranfdev.DistroShelf') @('flatpak install --assumeyes --sideload-repo=TRACK_SIDELOAD flathub com.ranfdev.DistroShelf') @(New-StageTest 'distroshelf-install' 'flatpak info com.ranfdev.DistroShelf') 'flatpak-sideload' 'com.ranfdev.DistroShelf' 'dependency' 'apps'),
        (New-StageContract 'terminals' @('rootfs') 'apt' @('apt-get update','apt-get download gnome-console gnome-terminal konsole kitty alacritty foot') @('apt-get -y install gnome-console gnome-terminal konsole kitty alacritty foot') @((New-StageTest 'gnome-console' 'command -v gnome-console'),(New-StageTest 'gnome-terminal' 'command -v gnome-terminal'),(New-StageTest 'konsole' 'command -v konsole'),(New-StageTest 'kitty' 'command -v kitty'),(New-StageTest 'alacritty' 'command -v alacritty'),(New-StageTest 'foot' 'command -v foot')) @('apt-get -y install --no-download gnome-console gnome-terminal konsole kitty alacritty foot') @((New-StageTest 'gnome-console' 'command -v gnome-console'),(New-StageTest 'gnome-terminal' 'command -v gnome-terminal'),(New-StageTest 'konsole' 'command -v konsole'),(New-StageTest 'kitty' 'command -v kitty'),(New-StageTest 'alacritty' 'command -v alacritty'),(New-StageTest 'foot' 'command -v foot')) 'apt-cache' '' 'terminal-set' 'terminals')
    )
}

function Get-DistroShelfPacmanStages {
    return @(
        (New-StageContract 'rootfs' @() 'pacman' @() @() @(New-StageTest 'os-release' 'test -s /etc/os-release') @() @() 'none' '' 'rootfs' 'bootstrap'),
        (New-StageContract 'podman' @('rootfs') 'pacman' @('pacman -Sy --noconfirm','pacman -Sw --noconfirm podman') @('pacman -S --noconfirm podman') @((New-StageTest 'podman-command' 'command -v podman'),(New-StageTest 'podman-version' 'podman --version'),(New-StageTest 'podman-info' 'podman info --format json')) @('pacman -U --noconfirm /track/packages/*.pkg.tar.*') @((New-StageTest 'podman-command' 'command -v podman'),(New-StageTest 'podman-version' 'podman --version')) 'pacman-cache' '' 'dependency' 'container-runtime'),
        (New-StageContract 'distrobox' @('rootfs','podman') 'pacman' @('pacman -Sw --noconfirm distrobox') @('pacman -S --noconfirm distrobox') @((New-StageTest 'distrobox-command' 'command -v distrobox'),(New-StageTest 'distrobox-version' 'distrobox --version')) @('pacman -U --noconfirm /track/packages/*.pkg.tar.*') @((New-StageTest 'distrobox-command' 'command -v distrobox')) 'pacman-cache' '' 'dependency' 'container-runtime'),
        (New-StageContract 'flatpak' @('rootfs') 'pacman' @('pacman -Sw --noconfirm flatpak') @('pacman -S --noconfirm flatpak') @((New-StageTest 'flatpak-command' 'command -v flatpak'),(New-StageTest 'flatpak-version' 'flatpak --version')) @('pacman -U --noconfirm /track/packages/*.pkg.tar.*') @((New-StageTest 'flatpak-command' 'command -v flatpak')) 'pacman-cache' '' 'dependency' 'desktop-runtime'),
        (New-StageContract 'flathub' @('rootfs','flatpak') 'pacman' @('mkdir -p /tmp/ds-flathub; curl -fsSL https://dl.flathub.org/repo/flathub.flatpakrepo -o /tmp/ds-flathub/flathub.flatpakrepo') @('flatpak remote-add --if-not-exists flathub /tmp/ds-flathub/flathub.flatpakrepo') @(New-StageTest 'flathub-remote' 'flatpak remotes --columns=name | grep -Fx flathub') @() @(New-StageTest 'flathub-remote' 'flatpak remotes --columns=name | grep -Fx flathub') 'wsl-path' '/tmp/ds-flathub' 'dependency' 'desktop-runtime'),
        (New-StageContract 'distroshelf' @('rootfs','distrobox','flatpak','flathub') 'pacman' @('flatpak install -y flathub com.ranfdev.DistroShelf') @() @(New-StageTest 'distroshelf-install' 'flatpak info com.ranfdev.DistroShelf') @('flatpak install --assumeyes --sideload-repo=TRACK_SIDELOAD flathub com.ranfdev.DistroShelf') @(New-StageTest 'distroshelf-install' 'flatpak info com.ranfdev.DistroShelf') 'flatpak-sideload' 'com.ranfdev.DistroShelf' 'dependency' 'apps'),
        (New-StageContract 'terminals' @('rootfs') 'pacman' @('pacman -Sw --noconfirm gnome-terminal konsole kitty alacritty foot') @('pacman -S --noconfirm gnome-terminal konsole kitty alacritty foot') @((New-StageTest 'gnome-terminal' 'command -v gnome-terminal'),(New-StageTest 'konsole' 'command -v konsole'),(New-StageTest 'kitty' 'command -v kitty'),(New-StageTest 'alacritty' 'command -v alacritty'),(New-StageTest 'foot' 'command -v foot')) @('pacman -U --noconfirm /track/packages/*.pkg.tar.*') @((New-StageTest 'terminal-artifacts' 'command -v gnome-terminal || command -v konsole || command -v kitty || command -v alacritty || command -v foot')) 'pacman-cache' '' 'terminal-set' 'terminals')
    )
}

function Get-DistroShelfRpmStages {
    param([string]$Distro,[ValidateSet('dnf','zypper')][string]$Manager)
    return @(
        (New-StageContract 'rootfs' @() $Manager @() @() @(New-StageTest 'os-release' 'test -s /etc/os-release') @() @() 'none' '' 'rootfs' 'bootstrap'),
        (New-StageContract 'podman' @('rootfs') $Manager @("$Manager -y install --downloadonly podman") @("$Manager -y install podman") @((New-StageTest 'podman-command' 'command -v podman'),(New-StageTest 'podman-version' 'podman --version'),(New-StageTest 'podman-info' 'podman info --format json')) @("$Manager -y install --cacheonly podman") @((New-StageTest 'podman-command' 'command -v podman'),(New-StageTest 'podman-version' 'podman --version')) 'rpm-cache' '' 'dependency' 'container-runtime'),
        (New-StageContract 'distrobox' @('rootfs','podman') $Manager @("$Manager -y install --downloadonly distrobox") @("$Manager -y install distrobox") @((New-StageTest 'distrobox-command' 'command -v distrobox'),(New-StageTest 'distrobox-version' 'distrobox --version')) @("$Manager -y install --cacheonly distrobox") @((New-StageTest 'distrobox-command' 'command -v distrobox')) 'rpm-cache' '' 'dependency' 'container-runtime'),
        (New-StageContract 'flatpak' @('rootfs') $Manager @("$Manager -y install --downloadonly flatpak") @("$Manager -y install flatpak") @((New-StageTest 'flatpak-command' 'command -v flatpak'),(New-StageTest 'flatpak-version' 'flatpak --version')) @("$Manager -y install --cacheonly flatpak") @((New-StageTest 'flatpak-command' 'command -v flatpak')) 'rpm-cache' '' 'dependency' 'desktop-runtime'),
        (New-StageContract 'flathub' @('rootfs','flatpak') $Manager @('mkdir -p /tmp/ds-flathub; curl -fsSL https://dl.flathub.org/repo/flathub.flatpakrepo -o /tmp/ds-flathub/flathub.flatpakrepo') @('flatpak remote-add --if-not-exists flathub /tmp/ds-flathub/flathub.flatpakrepo') @(New-StageTest 'flathub-remote' 'flatpak remotes --columns=name | grep -Fx flathub') @() @(New-StageTest 'flathub-remote' 'flatpak remotes --columns=name | grep -Fx flathub') 'wsl-path' '/tmp/ds-flathub' 'dependency' 'desktop-runtime'),
        (New-StageContract 'distroshelf' @('rootfs','distrobox','flatpak','flathub') $Manager @('flatpak install -y flathub com.ranfdev.DistroShelf') @() @(New-StageTest 'distroshelf-install' 'flatpak info com.ranfdev.DistroShelf') @('flatpak install --assumeyes --sideload-repo=TRACK_SIDELOAD flathub com.ranfdev.DistroShelf') @(New-StageTest 'distroshelf-install' 'flatpak info com.ranfdev.DistroShelf') 'flatpak-sideload' 'com.ranfdev.DistroShelf' 'dependency' 'apps'),
        (New-StageContract 'terminals' @('rootfs') $Manager @() @() @(New-StageTest 'terminal-directory' 'test -d /usr/bin') @() @(New-StageTest 'terminal-artifacts' 'find /usr/bin -maxdepth 1 -type f | grep -E "(gnome-terminal|kitty|alacritty|konsole|foot)$"') 'rpm-cache' '' 'terminal-set' 'terminals')
    )
}

$script:DistroShelfDistroDefinitions=@{
    'Ubuntu'=@{Id='Ubuntu';Track='Ubuntu0';PackageManager='apt';Rootfs=@{Name='Ubuntu';Architecture='amd64'};Stages=(Get-DistroShelfAptStages 'Ubuntu');TrackFinalTests=@(New-StageTest 'wsl-rootfs' 'test -s /etc/os-release';New-StageTest 'podman-functional' 'podman run --rm docker.io/library/alpine:latest true';New-StageTest 'distrobox-functional' 'distrobox list --no-color');ProfileFinalTests=@(New-StageTest 'profile-os' 'test -s /etc/os-release')}
    'Debian'=@{Id='Debian';Track='Debian0';PackageManager='apt';Rootfs=@{Name='Debian';Architecture='amd64'};Stages=(Get-DistroShelfAptStages 'Debian');TrackFinalTests=@(New-StageTest 'wsl-rootfs' 'test -s /etc/os-release';New-StageTest 'podman-functional' 'podman run --rm docker.io/library/alpine:latest true';New-StageTest 'distrobox-functional' 'distrobox list --no-color');ProfileFinalTests=@(New-StageTest 'profile-os' 'test -s /etc/os-release')}
    'Fedora'=@{Id='Fedora';Track='Fedora0';PackageManager='dnf';Rootfs=@{Name='Fedora';Architecture='amd64'};Stages=(Get-DistroShelfRpmStages 'Fedora' 'dnf');TrackFinalTests=@(New-StageTest 'wsl-rootfs' 'test -s /etc/os-release';New-StageTest 'podman-functional' 'podman run --rm docker.io/library/alpine:latest true');ProfileFinalTests=@(New-StageTest 'profile-os' 'test -s /etc/os-release')}
    'Arch Linux'=@{Id='Arch Linux';Track='ArchLinux0';PackageManager='pacman';Rootfs=@{Name='Arch Linux';Architecture='amd64'};Stages=(Get-DistroShelfPacmanStages);TrackFinalTests=@(New-StageTest 'wsl-rootfs' 'test -s /etc/os-release';New-StageTest 'podman-functional' 'podman run --rm docker.io/library/alpine:latest true');ProfileFinalTests=@(New-StageTest 'profile-os' 'test -s /etc/os-release')}
    'openSUSE'=@{Id='openSUSE';Track='openSUSE0';PackageManager='zypper';Rootfs=@{Name='openSUSE';Architecture='amd64'};Stages=(Get-DistroShelfRpmStages 'openSUSE' 'zypper');TrackFinalTests=@(New-StageTest 'wsl-rootfs' 'test -s /etc/os-release';New-StageTest 'podman-functional' 'podman run --rm docker.io/library/alpine:latest true');ProfileFinalTests=@(New-StageTest 'profile-os' 'test -s /etc/os-release')}
}
function Get-DistroShelfDistroDefinition {param([Parameter(Mandatory)][string]$Distro) if(!$script:DistroShelfDistroDefinitions.ContainsKey($Distro)){throw "Unsupported distro: $Distro"};$script:DistroShelfDistroDefinitions[$Distro]}
function Get-DistroShelfDistroStages {param([Parameter(Mandatory)][string]$Distro)return @(Get-DistroShelfDistroDefinition $Distro).Stages}
