# DistroShelf for Windows - beginner-friendly detection and profile GUI
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()

$script:Root=Split-Path -Parent $MyInvocation.MyCommand.Path
. (Join-Path $script:Root 'InstallOrchestrator.ps1')
$script:SupportedWslDistros=@('Ubuntu','Debian','Fedora','Arch Linux','openSUSE')
$script:SupportedDistroShelfTerminals=@('Alacritty','COSMIC Terminal','Deepin Terminal','Foot','GNOME Console','GNOME Terminal','Ghostty','Kitty','Konsole','Ptyxis','QTerminal')
$script:SelectedDistro='Ubuntu';$script:SelectedProfileId=$null;$script:PendingProfile=$null

function Get-WslDistros { try{return @((& wsl.exe --list --quiet 2>$null)|%{($_ -replace "`0",'').Trim()}|?{$_})}catch{return @()} }
function Get-SelectedProfile { if($script:SelectedProfileId -eq '__NEW__'){return $script:PendingProfile};if(!$script:SelectedProfileId){return $null};return Get-DistroShelfProfileById -Id $script:SelectedProfileId }
function Find-ProfileWslName([object]$p){if(!$p -or !$p.WslName){return $null};return @(Get-WslDistros|?{$_ -eq [string]$p.WslName})|Select-Object -First 1}
function Invoke-WslCommand([string]$cmd){$p=Get-SelectedProfile;$n=Find-ProfileWslName $p;if(!$n){return $null};try{$o=& wsl.exe --distribution $n -- bash -lc $cmd 2>$null;if($LASTEXITCODE -eq 0){return ($o -join "`n").Trim()}}catch{};return $null}
function Test-Wsl2 {try{$x=@(& wsl.exe --list -- verbose 2>&1)-replace "`0",'';if($x -match '\s2\s*$'){return 'Installed (WSL 2)'};$s=(@(& wsl.exe --status 2>&1)-join "`n")-replace "`0",'';if($s -match '(?im)Default Version\s*:\s*2'){return 'Installed (WSL 2 default)'}}catch{};return 'Not installed'}
function Test-LinuxCommand([string]$c){$p=Get-SelectedProfile;if(!$p){return "Needs $($script:SelectedDistro)"};if($p.IsNew){return 'Not installed'};if(!(Find-ProfileWslName $p)){return "Needs $($p.Name)"};if(Invoke-WslCommand "command -v '$c'"){return 'Installed'};return 'Not installed'}
function Test-Flathub {$p=Get-SelectedProfile;if(!$p){return "Needs $($script:SelectedDistro)"};if($p.IsNew){return 'Not configured'};if(!(Find-ProfileWslName $p)){return "Needs $($p.Name)"};if(Invoke-WslCommand "flatpak remotes --columns=name 2>/dev/null|grep -Fx flathub"){return 'Configured'};return 'Not configured'}
function Test-DistroShelf {$p=Get-SelectedProfile;if(!$p){return "Needs $($script:SelectedDistro)"};if($p.IsNew){return 'Not installed'};if(!(Find-ProfileWslName $p)){return "Needs $($p.Name)"};if(Invoke-WslCommand 'flatpak info com.ranfdev.DistroShelf >/dev/null 2>&1'){return 'Installed'};return 'Not installed'}
function Test-WindowsCommand([string]$c){try{Get-Command $c -EA Stop|Out-Null;return 'Installed'}catch{return 'Not installed'}}
function Get-ProfileDisplayText([object]$p){if(!$p){return ''};if($p.IsNew){return "$($p.Name) - Not installed"};switch([string]$p.Status){'Ready'{return "$($p.Name) - Installed"};'Installation failed'{return "$($p.Name) - Failed"};default{return "$($p.Name) - Not installed"}}}
function Get-NextProfilePreview([string]$d){$def=Get-DistroShelfProfileDefinition $d;$highest=0;foreach($p in @(Get-DistroShelfProfiles|?{[string]$_.Distro -eq $d -and [string]$_.Status -ne 'Pending'})){if([string]$p.Name -match '([0-9]+)$'){$highest=[Math]::Max($highest,[int]$Matches[1])}};$n=$highest+1;return [pscustomobject]@{Id='__NEW__';Name="$($def.WslBaseName)$n";Distro=$d;WslName="DistroShelf-$($def.WslBaseName)$n";Status='Pending';IsNew=$true;PackageManager=$def.PackageManager}}
function Refresh-ProfileChoices {$profileCombo.Items.Clear();$profiles=@(Get-DistroShelfProfiles|?{[string]$_.Distro -eq $script:SelectedDistro -and [string]$_.Status -ne 'Pending'});foreach($p in $profiles){[void]$profileCombo.Items.Add([pscustomobject]@{Text=Get-ProfileDisplayText $p;Id=[string]$p.Id})};$script:PendingProfile=Get-NextProfilePreview $script:SelectedDistro;[void]$profileCombo.Items.Add([pscustomobject]@{Text=Get-ProfileDisplayText $script:PendingProfile;Id='__NEW__'});$idx=$profileCombo.Items.Count-1;if($script:SelectedProfileId -and $script:SelectedProfileId -ne '__NEW__'){for($i=0;$i-lt$profileCombo.Items.Count;$i++){if([string]$profileCombo.Items[$i].Id -eq [string]$script:SelectedProfileId){$idx=$i;break}}};$profileCombo.SelectedIndex=$idx}

$form=New-Object System.Windows.Forms.Form;$form.Text='DistroShelf for Windows';$form.StartPosition='CenterScreen';$form.Size=New-Object System.Drawing.Size(760,740);$form.MinimumSize=New-Object System.Drawing.Size(700,680)
$t=New-Object System.Windows.Forms.Label;$t.Text='DistroShelf for Windows';$t.Font=New-Object System.Drawing.Font('Segoe UI',20,[System.Drawing.FontStyle]::Bold);$t.Location=New-Object System.Drawing.Point(24,18);$t.AutoSize=$true;$form.Controls.Add($t)
$s=New-Object System.Windows.Forms.Label;$s.Text='Detect and manage isolated Linux environments on Windows.';$s.Location=New-Object System.Drawing.Point(28,58);$s.AutoSize=$true;$form.Controls.Add($s)
$table=New-Object System.Windows.Forms.TableLayoutPanel;$table.Location=New-Object System.Drawing.Point(24,92);$table.Size=New-Object System.Drawing.Size(696,470);$table.ColumnCount=3;$table.RowCount=1;$table.CellBorderStyle='None';$table.BackColor=[System.Drawing.Color]::White;$table.ColumnStyles.Add((New-Object System.Windows.Forms.ColumnStyle([System.Windows.Forms.SizeType]::Absolute,220)));$table.ColumnStyles.Add((New-Object System.Windows.Forms.ColumnStyle([System.Windows.Forms.SizeType]::Absolute,110)));$table.ColumnStyles.Add((New-Object System.Windows.Forms.ColumnStyle([System.Windows.Forms.SizeType]::Percent,100)));$form.Controls.Add($table)
function Header([string]$x,[int]$c){$l=New-Object System.Windows.Forms.Label;$l.Text=$x;$l.Dock='Fill';$l.Padding=New-Object System.Windows.Forms.Padding(8,0,0,0);$l.TextAlign='MiddleLeft';[void]$table.Controls.Add($l,$c,0)};Header Component 0;Header Category 1;Header Status 2
$script:Components=@(@{Key='wsl2';Name='WSL 2';Group='Core';Detect={Test-Wsl2}},@{Key='podman';Name='Podman';Group='Core';Detect={Test-LinuxCommand podman}},@{Key='distrobox';Name='Distrobox';Group='Core';Detect={Test-LinuxCommand distrobox}},@{Key='flatpak';Name='Flatpak';Group='GUI';Detect={Test-LinuxCommand flatpak}},@{Key='flathub';Name='Flathub';Group='GUI';Detect={Test-Flathub}},@{Key='distroshelf';Name='DistroShelf';Group='GUI';Detect={Test-DistroShelf}},@{Key='git';Name='Git for Windows';Group='Developer';Detect={Test-WindowsCommand git.exe}})
function Add-Component([hashtable]$c){$r=$table.RowCount;$table.RowCount++;$table.RowStyles.Add((New-Object System.Windows.Forms.RowStyle([System.Windows.Forms.SizeType]::Absolute,34)));$cb=New-Object System.Windows.Forms.CheckBox;$cb.Text=$c.Name;$cb.Tag=$c;$cb.Dock='Fill';$cb.Padding=New-Object System.Windows.Forms.Padding(8,0,0,0);[void]$table.Controls.Add($cb,0,$r);$cat=New-Object System.Windows.Forms.Label;$cat.Text=$c.Group;$cat.Dock='Fill';$cat.TextAlign='MiddleLeft';[void]$table.Controls.Add($cat,1,$r);$st=New-Object System.Windows.Forms.Label;$st.Dock='Fill';$st.TextAlign='MiddleLeft';$st.Tag=$c.Key;[void]$table.Controls.Add($st,2,$r)}
Add-Component $script:Components[0]
$r=$table.RowCount;$table.RowCount++;$table.RowStyles.Add((New-Object System.Windows.Forms.RowStyle([System.Windows.Forms.SizeType]::Absolute,34)));$dc=New-Object System.Windows.Forms.CheckBox;$dc.Text='Distro options';$dc.Dock='Fill';$dc.Padding=New-Object System.Windows.Forms.Padding(8,0,0,0);[void]$table.Controls.Add($dc,0,$r);$dl=New-Object System.Windows.Forms.Label;$dl.Text='Core';$dl.Dock='Fill';$dl.TextAlign='MiddleLeft';[void]$table.Controls.Add($dl,1,$r);$distroCombo=New-Object System.Windows.Forms.ComboBox;$distroCombo.Dock='Fill';$distroCombo.DropDownStyle='DropDownList';$distroCombo.Margin=New-Object System.Windows.Forms.Padding(0,4,8,4);foreach($d in $script:SupportedWslDistros){[void]$distroCombo.Items.Add($d)};$distroCombo.SelectedItem=$script:SelectedDistro;[void]$table.Controls.Add($distroCombo,2,$r)
$r=$table.RowCount;$table.RowCount++;$table.RowStyles.Add((New-Object System.Windows.Forms.RowStyle([System.Windows.Forms.SizeType]::Absolute,34)));$pl=New-Object System.Windows.Forms.Label;$pl.Text='Profile';$pl.Dock='Fill';$pl.Padding=New-Object System.Windows.Forms.Padding(8,0,0,0);$pl.TextAlign='MiddleLeft';[void]$table.Controls.Add($pl,0,$r);$pc=New-Object System.Windows.Forms.Label;$pc.Text='Core';$pc.Dock='Fill';$pc.TextAlign='MiddleLeft';[void]$table.Controls.Add($pc,1,$r);$profileCombo=New-Object System.Windows.Forms.ComboBox;$profileCombo.Dock='Fill';$profileCombo.DropDownStyle='DropDownList';$profileCombo.Margin=New-Object System.Windows.Forms.Padding(0,4,8,4);$profileCombo.DisplayMember='Text';[void]$table.Controls.Add($profileCombo,2,$r)
foreach($c in $script:Components[1..4]){Add-Component $c}
$r=$table.RowCount;$table.RowCount++;$table.RowStyles.Add((New-Object System.Windows.Forms.RowStyle([System.Windows.Forms.SizeType]::Absolute,34)));$tl=New-Object System.Windows.Forms.Label;$tl.Text='Terminal Preference for DistroShelf';$tl.Dock='Fill';$tl.Padding=New-Object System.Windows.Forms.Padding(8,0,0,0);$tl.TextAlign='MiddleLeft';[void]$table.Controls.Add($tl,0,$r);$tc=New-Object System.Windows.Forms.Label;$tc.Text='GUI';$tc.Dock='Fill';$tc.TextAlign='MiddleLeft';[void]$table.Controls.Add($tc,1,$r);$terminalCombo=New-Object System.Windows.Forms.ComboBox;$terminalCombo.Dock='Fill';$terminalCombo.DropDownStyle='DropDownList';$terminalCombo.Margin=New-Object System.Windows.Forms.Padding(0,4,8,4);foreach($x in $script:SupportedDistroShelfTerminals){[void]$terminalCombo.Items.Add($x)};$terminalCombo.SelectedItem='GNOME Console';[void]$table.Controls.Add($terminalCombo,2,$r)
Add-Component $script:Components[5];Add-Component $script:Components[6]
$refresh=New-Object System.Windows.Forms.Button;$refresh.Text='Scan again';$refresh.Location=New-Object System.Drawing.Point(24,610);$refresh.Size=New-Object System.Drawing.Size(120,38);$form.Controls.Add($refresh);$install=New-Object System.Windows.Forms.Button;$install.Text='Install selected';$install.Location=New-Object System.Drawing.Point(155,610);$install.Size=New-Object System.Drawing.Size(140,38);$form.Controls.Add($install);$info=New-Object System.Windows.Forms.Label;$info.Text='Select a Linux distribution. The next profile is shown without being saved until installation.';$info.Location=New-Object System.Drawing.Point(24,660);$info.Size=New-Object System.Drawing.Size(696,40);$form.Controls.Add($info)
function Refresh-Scan {$p=Get-SelectedProfile;foreach($control in $table.Controls){if($control -is [System.Windows.Forms.CheckBox] -and $control.Tag){$c=$control.Tag;$st=& $c.Detect;foreach($child in $table.Controls){if($child -is [System.Windows.Forms.Label] -and $child.Tag -eq $c.Key){$child.Text=$st;if($st -like 'Installed*' -or $st -eq 'Configured'){$child.ForeColor=[System.Drawing.Color]::Green}else{$child.ForeColor=[System.Drawing.SystemColors]::ControlText};break}};$control.Checked=($st -notlike 'Installed*' -and $st -ne 'Configured')}};$dc.Checked=($p -and $p.Status -ne 'Ready');if($p){$info.Text="Profile: $($p.Name) - $(if($p.IsNew){'Not installed'}else{$p.Status})"}}
$profileCombo.Add_SelectedIndexChanged({if($profileCombo.SelectedItem){$script:SelectedProfileId=[string]$profileCombo.SelectedItem.Id;Refresh-Scan}})
$distroCombo.Add_SelectedIndexChanged({if($distroCombo.SelectedItem){$script:SelectedDistro=[string]$distroCombo.SelectedItem;$script:SelectedProfileId=$null;Refresh-ProfileChoices;Refresh-Scan}})
$refresh.Add_Click({Refresh-ProfileChoices;Refresh-Scan})
$install.Add_Click({$p=Get-SelectedProfile;if(!$p){[System.Windows.Forms.MessageBox]::Show('Please select a profile.','DistroShelf');return};if(!$p.IsNew -and [string]$p.Status -eq 'Ready'){[System.Windows.Forms.MessageBox]::Show("$($p.Name) is already installed. Select the next Not installed profile entry to create another independent environment.",'DistroShelf');return};$selected=@($table.Controls|?{$_ -is [System.Windows.Forms.CheckBox] -and $_.Tag -and $_.Checked});if(!$selected.Count){[System.Windows.Forms.MessageBox]::Show('Nothing is selected for installation.','DistroShelf');return};$pf=New-Object System.Windows.Forms.Form;$pf.Text="Installing $($p.Name)";$pf.StartPosition='CenterParent';$pf.Size=New-Object System.Drawing.Size(520,190);$pf.ControlBox=$false;$lab=New-Object System.Windows.Forms.Label;$lab.Text='Preparing...';$lab.Location=New-Object System.Drawing.Point(20,20);$lab.Size=New-Object System.Drawing.Size(460,45);$pf.Controls.Add($lab);$bar=New-Object System.Windows.Forms.ProgressBar;$bar.Location=New-Object System.Drawing.Point(20,75);$bar.Size=New-Object System.Drawing.Size(460,25);$pf.Controls.Add($bar);$close=New-Object System.Windows.Forms.Button;$close.Text='Close';$close.Enabled=$false;$close.Location=New-Object System.Drawing.Point(380,115);$close.Size=New-Object System.Drawing.Size(100,30);$pf.Controls.Add($close);$form.Enabled=$false;$pf.Show($form);try{if($p.IsNew){$p=New-DistroShelfProfile -Distro $script:SelectedDistro;$script:SelectedProfileId=[string]$p.Id;$script:PendingProfile=$null};$result=Invoke-DistroShelfInstall -Distro $script:SelectedDistro -ProfileId ([string]$p.Id) -Terminal ([string]$terminalCombo.SelectedItem) -OnProgress {param($pct,$msg)$bar.Value=[Math]::Min(100,[Math]::Max(0,$pct));$lab.Text=$msg;$pf.Refresh()};if($result.Success){$lab.Text='Installation complete!';$bar.Value=100;[System.Windows.Forms.MessageBox]::Show("DistroShelf is ready in $($result.ProfileName).",'Installation complete','OK','Information')|Out-Null}else{[System.Windows.Forms.MessageBox]::Show($result.Error,'Installation failed','OK','Error')|Out-Null}}catch{[System.Windows.Forms.MessageBox]::Show($_.Exception.Message,'Installation failed','OK','Error')|Out-Null}finally{$form.Enabled=$true;$close.Enabled=$true;$pf.ControlBox=$true;$pf.Refresh();Refresh-ProfileChoices;Refresh-Scan}})
Refresh-ProfileChoices;Refresh-Scan;[void]$form.ShowDialog()
